/**
 * ABI origin: explorer.
 * Complete verified MetaMorpho V1.1 ABI copied mechanically from:
 * https://monadscan.com/address/0x32841A8511D5c2c5b253f45668780B99139e476D#code
 * Retrieved 2026-07-15. Converted with abitype formatAbi; no entries were filtered.
 */
import { parseAbi } from "viem";

export const MetaMorphoV1_1Abi = parseAbi([
  "constructor(address owner, address morpho, uint256 initialTimelock, address _asset, string __name, string __symbol)",
  "error AboveMaxTimelock()",
  "error AddressEmptyCode(address target)",
  "error AddressInsufficientBalance(address account)",
  "error AllCapsReached()",
  "error AlreadyPending()",
  "error AlreadySet()",
  "error BelowMinTimelock()",
  "error DuplicateMarket(bytes32 id)",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error ERC20InsufficientAllowance(address spender, uint256 allowance, uint256 needed)",
  "error ERC20InsufficientBalance(address sender, uint256 balance, uint256 needed)",
  "error ERC20InvalidApprover(address approver)",
  "error ERC20InvalidReceiver(address receiver)",
  "error ERC20InvalidSender(address sender)",
  "error ERC20InvalidSpender(address spender)",
  "error ERC2612ExpiredSignature(uint256 deadline)",
  "error ERC2612InvalidSigner(address signer, address owner)",
  "error ERC4626ExceededMaxDeposit(address receiver, uint256 assets, uint256 max)",
  "error ERC4626ExceededMaxMint(address receiver, uint256 shares, uint256 max)",
  "error ERC4626ExceededMaxRedeem(address owner, uint256 shares, uint256 max)",
  "error ERC4626ExceededMaxWithdraw(address owner, uint256 assets, uint256 max)",
  "error FailedInnerCall()",
  "error InconsistentAsset(bytes32 id)",
  "error InconsistentReallocation()",
  "error InvalidAccountNonce(address account, uint256 currentNonce)",
  "error InvalidMarketRemovalNonZeroCap(bytes32 id)",
  "error InvalidMarketRemovalNonZeroSupply(bytes32 id)",
  "error InvalidMarketRemovalTimelockNotElapsed(bytes32 id)",
  "error InvalidShortString()",
  "error MarketNotCreated()",
  "error MarketNotEnabled(bytes32 id)",
  "error MathOverflowedMulDiv()",
  "error MaxFeeExceeded()",
  "error MaxQueueLengthExceeded()",
  "error NoPendingValue()",
  "error NonZeroCap()",
  "error NotAllocatorRole()",
  "error NotCuratorNorGuardianRole()",
  "error NotCuratorRole()",
  "error NotEnoughLiquidity()",
  "error NotGuardianRole()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error PendingCap(bytes32 id)",
  "error PendingRemoval()",
  "error SafeCastOverflowedUintDowncast(uint8 bits, uint256 value)",
  "error SafeERC20FailedOperation(address token)",
  "error StringTooLong(string str)",
  "error SupplyCapExceeded(bytes32 id)",
  "error TimelockNotElapsed()",
  "error UnauthorizedMarket(bytes32 id)",
  "error ZeroAddress()",
  "error ZeroFeeRecipient()",
  "event AccrueInterest(uint256 newTotalAssets, uint256 feeShares)",
  "event Approval(address indexed owner, address indexed spender, uint256 value)",
  "event Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)",
  "event EIP712DomainChanged()",
  "event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event ReallocateSupply(address indexed caller, bytes32 indexed id, uint256 suppliedAssets, uint256 suppliedShares)",
  "event ReallocateWithdraw(address indexed caller, bytes32 indexed id, uint256 withdrawnAssets, uint256 withdrawnShares)",
  "event RevokePendingCap(address indexed caller, bytes32 indexed id)",
  "event RevokePendingGuardian(address indexed caller)",
  "event RevokePendingMarketRemoval(address indexed caller, bytes32 indexed id)",
  "event RevokePendingTimelock(address indexed caller)",
  "event SetCap(address indexed caller, bytes32 indexed id, uint256 cap)",
  "event SetCurator(address indexed newCurator)",
  "event SetFee(address indexed caller, uint256 newFee)",
  "event SetFeeRecipient(address indexed newFeeRecipient)",
  "event SetGuardian(address indexed caller, address indexed guardian)",
  "event SetIsAllocator(address indexed allocator, bool isAllocator)",
  "event SetName(string name)",
  "event SetSkimRecipient(address indexed newSkimRecipient)",
  "event SetSupplyQueue(address indexed caller, bytes32[] newSupplyQueue)",
  "event SetSymbol(string symbol)",
  "event SetTimelock(address indexed caller, uint256 newTimelock)",
  "event SetWithdrawQueue(address indexed caller, bytes32[] newWithdrawQueue)",
  "event Skim(address indexed caller, address indexed token, uint256 amount)",
  "event SubmitCap(address indexed caller, bytes32 indexed id, uint256 cap)",
  "event SubmitGuardian(address indexed newGuardian)",
  "event SubmitMarketRemoval(address indexed caller, bytes32 indexed id)",
  "event SubmitTimelock(uint256 newTimelock)",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event UpdateLastTotalAssets(uint256 updatedTotalAssets)",
  "event UpdateLostAssets(uint256 newLostAssets)",
  "event Withdraw(address indexed sender, address indexed receiver, address indexed owner, uint256 assets, uint256 shares)",
  "function DECIMALS_OFFSET() view returns (uint8)",
  "function DOMAIN_SEPARATOR() view returns (bytes32)",
  "function MORPHO() view returns (address)",
  "function acceptCap((address loanToken, address collateralToken, address oracle, address irm, uint256 lltv) marketParams)",
  "function acceptGuardian()",
  "function acceptOwnership()",
  "function acceptTimelock()",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function asset() view returns (address)",
  "function balanceOf(address account) view returns (uint256)",
  "function config(bytes32) view returns (uint184 cap, bool enabled, uint64 removableAt)",
  "function convertToAssets(uint256 shares) view returns (uint256)",
  "function convertToShares(uint256 assets) view returns (uint256)",
  "function curator() view returns (address)",
  "function decimals() view returns (uint8)",
  "function deposit(uint256 assets, address receiver) returns (uint256 shares)",
  "function eip712Domain() view returns (bytes1 fields, string name, string version, uint256 chainId, address verifyingContract, bytes32 salt, uint256[] extensions)",
  "function fee() view returns (uint96)",
  "function feeRecipient() view returns (address)",
  "function guardian() view returns (address)",
  "function isAllocator(address) view returns (bool)",
  "function lastTotalAssets() view returns (uint256)",
  "function lostAssets() view returns (uint256)",
  "function maxDeposit(address) view returns (uint256)",
  "function maxMint(address) view returns (uint256)",
  "function maxRedeem(address owner) view returns (uint256)",
  "function maxWithdraw(address owner) view returns (uint256 assets)",
  "function mint(uint256 shares, address receiver) returns (uint256 assets)",
  "function multicall(bytes[] data) returns (bytes[] results)",
  "function name() view returns (string)",
  "function nonces(address owner) view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingCap(bytes32) view returns (uint192 value, uint64 validAt)",
  "function pendingGuardian() view returns (address value, uint64 validAt)",
  "function pendingOwner() view returns (address)",
  "function pendingTimelock() view returns (uint192 value, uint64 validAt)",
  "function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)",
  "function previewDeposit(uint256 assets) view returns (uint256)",
  "function previewMint(uint256 shares) view returns (uint256)",
  "function previewRedeem(uint256 shares) view returns (uint256)",
  "function previewWithdraw(uint256 assets) view returns (uint256)",
  "function reallocate(((address loanToken, address collateralToken, address oracle, address irm, uint256 lltv) marketParams, uint256 assets)[] allocations)",
  "function redeem(uint256 shares, address receiver, address owner) returns (uint256 assets)",
  "function renounceOwnership()",
  "function revokePendingCap(bytes32 id)",
  "function revokePendingGuardian()",
  "function revokePendingMarketRemoval(bytes32 id)",
  "function revokePendingTimelock()",
  "function setCurator(address newCurator)",
  "function setFee(uint256 newFee)",
  "function setFeeRecipient(address newFeeRecipient)",
  "function setIsAllocator(address newAllocator, bool newIsAllocator)",
  "function setName(string newName)",
  "function setSkimRecipient(address newSkimRecipient)",
  "function setSupplyQueue(bytes32[] newSupplyQueue)",
  "function setSymbol(string newSymbol)",
  "function skim(address token)",
  "function skimRecipient() view returns (address)",
  "function submitCap((address loanToken, address collateralToken, address oracle, address irm, uint256 lltv) marketParams, uint256 newSupplyCap)",
  "function submitGuardian(address newGuardian)",
  "function submitMarketRemoval((address loanToken, address collateralToken, address oracle, address irm, uint256 lltv) marketParams)",
  "function submitTimelock(uint256 newTimelock)",
  "function supplyQueue(uint256) view returns (bytes32)",
  "function supplyQueueLength() view returns (uint256)",
  "function symbol() view returns (string)",
  "function timelock() view returns (uint256)",
  "function totalAssets() view returns (uint256)",
  "function totalSupply() view returns (uint256)",
  "function transfer(address to, uint256 value) returns (bool)",
  "function transferFrom(address from, address to, uint256 value) returns (bool)",
  "function transferOwnership(address newOwner)",
  "function updateWithdrawQueue(uint256[] indexes)",
  "function withdraw(uint256 assets, address receiver, address owner) returns (uint256 shares)",
  "function withdrawQueue(uint256) view returns (bytes32)",
  "function withdrawQueueLength() view returns (uint256)",
]);
